require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

desc "Run tests"
RSpec::Core::RakeTask.new(:spec => ["ci:setup:rspec"]) do |t|
  ENV['CI_REPORTS'] = Dir.pwd+"/reports"
  t.pattern = 'spec/**/*_spec.rb'
end

task :default => :spec